version: "3"

services:
  core:
    container_name: core
    build:
      context: .
      dockerfile: ./services/core/prod.Dockerfile
      args:
        PROJECT: "@icptokens/core"
        PROJECT_FOLDER: core
        TURBO_TEAM: $TURBO_TEAM
        TURBO_TOKEN: $TURBO_TOKEN
      tags:
        - ghcr.io/cyberninjaslab/icp-tokens-node/core
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    stop_grace_period: 1s


  # postgres:
  #   container_name: postgres
  #   image: postgres:17
  #   restart: always
  #   environment:
  #     POSTGRES_USER: $POSTGRES_USER
  #     POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  #     POSTGRES_DB: $POSTGRES_DB
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - app_network
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

networks:
  app_network:
