version: "3"

services:
  core:
    container_name: core
    build:
      context: .
      dockerfile: ./services/core/prod.Dockerfile
      args:
        PROJECT: "@icptokens/core"
        PROJECT_FOLDER: core
        TURBO_TEAM: $TURBO_TEAM
        TURBO_TOKEN: $TURBO_TOKEN
      tags:
        - ghcr.io/cyberninjaslab/icp-tokens-node/core
    restart: always
    depends_on:
      - timescaledb
    ports:
      - 3000:3000
    networks:
      - app_network
    stop_grace_period: 1s


  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - timescale-data:/var/lib/postgresql/data
      - ./init.local.postgres.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  timescale-data: {}

networks:
  app_network:
