export const ALLOWED_TOKENS = [
  "ryjl3-tyaaa-aaaaa-aaaba-cai",
  "lkwrt-vyaaa-aaaaq-aadhq-cai",
  "o7oak-iyaaa-aaaaq-aadzq-cai",
  "mxzaz-hqaaa-aaaar-qaada-cai",
  // "2ouva-viaaa-aaaaq-aaamq-cai",
  // "tyyy3-4aaaa-aaaaq-aab7a-cai",
  // "zfcdd-tqaaa-aaaaq-aaaga-cai",
  // "xsi2v-cyaaa-aaaaq-aabfq-cai",
  // "7pail-xaaaa-aaaas-aabmq-cai",
  // "m6xut-mqaaa-aaaaq-aadua-cai",
  // "hhaaz-2aaaa-aaaaq-aacla-cai",
  // "buwm7-7yaaa-aaaar-qagva-cai",
  // "jcmow-hyaaa-aaaaq-aadlq-cai",
  // "atbfz-diaaa-aaaaq-aacyq-cai",
  // "ca6gz-lqaaa-aaaaq-aacwa-cai",
  // "6rdgd-kyaaa-aaaaq-aaavq-cai",
  // "73mez-iiaaa-aaaaq-aaasq-cai",
  // "k45jy-aiaaa-aaaaq-aadcq-cai",
  // "f54if-eqaaa-aaaaq-aacea-cai",
  // "rffwt-piaaa-aaaaq-aabqq-cai",
  // "ifwyg-gaaaa-aaaaq-aaeqq-cai",
  // "ss2fx-dyaaa-aaaar-qacoq-cai",
  // "bliq2-niaaa-aaaaq-aac4q-cai",
  // "druyg-tyaaa-aaaaq-aactq-cai",
  // "oj6if-riaaa-aaaaq-aaeha-cai",
  // "mih44-vaaaa-aaaaq-aaekq-cai",
  // "gemj7-oyaaa-aaaaq-aacnq-cai",
  // "o4zzi-qaaaa-aaaaq-aaeeq-cai",
  // "rh2pm-ryaaa-aaaan-qeniq-cai",
  // "ddsp7-7iaaa-aaaaq-aacqq-cai"
]; 